### ISSUE TITLE
UnhashableParamError: Cannot hash argument 'docs' (of type builtins.list) in 'embed_docs'.

### ISSUE THREAD

**Issue by victorhugor45** [davila7/file-gpt#1]
Hola Daniel Davila

Me pareció muy interesante file-gpr y quise probarla.
La clone, la instale de acuerdo al readme y después de un par de errores con el streamlit y la cache deprecada, la aplicación me levanta.

![image](https://user-images.githubusercontent.com/15006225/220445919-c60c5ea4-efaf-47c6-af27-79089378cf2d.png)

UnhashableParamError: Cannot hash argument 'docs' (of type builtins.list) in 'embed_docs'.

To address this, you can tell Streamlit not to hash this argument by adding a leading underscore to the argument's name in the function signature:

@st.cache_data
def embed_docs(_docs, ...):
    ...
Traceback:
File "C:\Users\vrodriguez\file-gpt\app.py", line 62, in <module>
    index = embed_docs(text)

**Comment by davila7** [comment]
@victorhugor45 con que versión de python la estás ejecutando?

**Comment by victorhugor45** [comment]
Python 3.10.2

**Comment by victorhugor45** [comment]
Recién  actualice la ultima versión Python 3.11.2, y el problema persiste.

**Comment by davila7** [comment]
Yo estoy trabajando en la versión 3.9 
Podrías probar con esa
