### ISSUE TITLE
Trouble running app.py

### ISSUE THREAD

**Issue by vinay-k12** [davila7/file-gpt#2]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/19322429/220666064-1e203a19-7f52-43f4-baa8-7a6eef3d8304.png">

Here is the snapshot of the stremlit error.

**Comment by uhuhh** [comment]
same problem, with Python 3.9.14 and redhat EL 9.1

**Comment by davila7** [comment]
@vinay-k12 @uhuhh 

I already fixed this problem... try again

**Comment by vinay-k12** [comment]
I just re ran it. Facing same issue. I am using stremlit cloud to host the app directly. 

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/19322429/220822385-cc5852c1-0937-43d5-8d83-f4b9f52e3c71.png">
